github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-process-model-service
      branch: 7.0.x
      useSinglePullRequest: true      
    - name: activiti-cloud-org-service
      branch: 7.0.x
      useSinglePullRequest: true      
    - name: activiti-cloud-modeling-dependencies
      branch: 7.0.x
      useSinglePullRequest: true      
      
