github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-process-model-service
      branch: develop
    - name: activiti-cloud-org-service
      branch: develop
    - name: activiti-cloud-modeling-dependencies
      branch: develop
      useSinglePullRequest: true      
      
